# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI test

on:
  push:
    branches: [ "main", "test-fix", "ci" ]
  pull_request:
    branches: [ "main", "test-fix" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Jest globally
        run: npm install -g jest

      - name: Start server and run tests
        env:
          DB_USERNAME: todolist_user
          DB_PASSWORD: complex_password
        run:
          npm install && node server.js & sleep 10 && npx jest
